include: package:very_good_analysis/analysis_options.yaml

# TODO: This temporarily disables the lint errors due to the strictness of 
# very_good_analysis. As the app stabilizes, this should be removed
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
